# Generated by Django 3.2.4 on 2021-06-14 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 11, 22, 15, 612607), verbose_name='date published'),
        ),
    ]
